### ISSUE TITLE
Feature: みこちの2023年の誕生日「特別｜スペシャルテーマ」

### ISSUE THREAD

**Issue by njtalba5127** [nejima-kensetsu/newojima#66]
<div align="center">

![image](https://user-images.githubusercontent.com/31657420/222198233-ddf95f60-6c1b-41ce-8213-65cca2b57692.png)

# みこちの2023年の誕生日 >.<｜さくらみこ生誕祭

</div>

### Todos

- [ ] みこちの動画 
  - [【 #さくらみこ生誕祭 】BIRTHDAY PARTY 🎂 4th Virtual3DLive !!【ホロライブ/さくらみこ】](https://www.youtube.com/watch?v=Cv_2tjVo-p4&ab_channel=MikoCh.%E3%81%95%E3%81%8F%E3%82%89%E3%81%BF%E3%81%93)
- [ ] New Color Theme | 特別｜スペシャルテーマ
- [ ] New Profile DP
- [ ] New Profile Description 説明
---
- [ ] Fix Bugs pls
  - [x] #65 
  - [x] #57 

---

## 書誌 References
- https://www.youtube.com/watch?v=Cv_2tjVo-p4&ab_channel=MikoCh.%E3%81%95%E3%81%8F%E3%82%89%E3%81%BF%E3%81%93

**Comment by njtalba5127** [comment]
https://user-images.githubusercontent.com/31657420/222224039-15ecddb8-0726-47e6-b8e7-664ddc1b608a.mp4

need to be larger and wider

**Comment by njtalba5127** [comment]
too late ;-; next time again
